import { vi } from 'vitest';

export const fetchUserQuarters = vi.fn().mockResolvedValue([]);
export const fetchUserWeeks = vi.fn().mockResolvedValue([]);
export const fetchWeekWithQuestions = vi.fn().mockResolvedValue(null);
export const fetchDashboardData = vi.fn().mockResolvedValue({ weeks: [], questions: [] });
export const createWeek = vi.fn().mockResolvedValue(null);
export const updateWeek = vi.fn().mockResolvedValue(true);
export const deleteWeek = vi.fn().mockResolvedValue(true);
export const addQuestion = vi.fn().mockResolvedValue(null);
export const deleteQuestion = vi.fn().mockResolvedValue(true);
export const saveAnswer = vi.fn().mockResolvedValue(true);
export const bulkImportQuestions = vi.fn().mockResolvedValue(true);
export const createProgressTracker = vi.fn().mockResolvedValue(null);
export const getTrackerForQuestion = vi.fn().mockResolvedValue(null);
export const fetchTrackerWithCheckIns = vi.fn().mockResolvedValue(null);
export const toggleCheckIn = vi.fn().mockResolvedValue(true);
export const updateCheckInNotes = vi.fn().mockResolvedValue(true);
export const deleteProgressTracker = vi.fn().mockResolvedValue(true);
export const createQuarter = vi.fn().mockResolvedValue(null);
export const updateQuarter = vi.fn().mockResolvedValue(true);
export const deleteQuarter = vi.fn().mockResolvedValue(true);
export const moveWeekToQuarter = vi.fn().mockResolvedValue(true);
export const copyWeekToQuarter = vi.fn().mockResolvedValue(null);
export const extractQuestionsFromImage = vi.fn().mockResolvedValue(null);
export const fetchUserTrackers = vi.fn().mockResolvedValue([]);
